# Mail Properties
property.mail.host=${env:SMTP_HOST}
property.mail.port=${env:SMTP_PORT}
property.mail.username=${env:SMTP_USER}
property.mail.password=${env:SMTP_PASS}
property.mail.to=${env:MAIL_TO}
property.mail.from=${env:MAIL_FROM}

# Console Appender
appender.console.type=Console
appender.console.name=Console
appender.console.target=SYSTEM_OUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%d{HH:mm:ss}] %-5p %c{1} - %m%n

# File Appender
appender.file.type=File
appender.file.name=FileLogger
appender.file.fileName=logs/app.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# SMTP Appender
appender.mail.type=SMTP
appender.mail.name=MailAppender
appender.mail.subject=LRP Application Error Detected!
appender.mail.to=${mail.to}
appender.mail.from=${mail.from}
appender.mail.smtpHost=${mail.host}
appender.mail.smtpPort=${mail.port}
appender.mail.smtpUsername=${mail.username}
appender.mail.smtpPassword=${mail.password}
appender.mail.bufferSize=512
appender.mail.smtpProtocol=smtps
appender.mail.layout.type=PatternLayout
appender.mail.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n
appender.mail.filter.threshold.type=ThresholdFilter
appender.mail.filter.threshold.level=fatal
appender.mail.filter.threshold.onMatch=ACCEPT
appender.mail.filter.threshold.onMismatch=DENY

# Root Logger
rootLogger.level=info
rootLogger.appenderRefs=file,mail,console
rootLogger.appenderRef.console.ref=Console
rootLogger.appenderRef.file.ref=FileLogger
rootLogger.appenderRef.mail.ref=MailAppender
